#####以下需要复制到config_local.yml中进行配置#####
# 环境
ENV: DEV
#  PRO
# DEV测试环境
DEV:
  baseURL: 'http://pp-m.njfae.com.cn/dist/#'
  # 订单号
  orderdetail: 'CM1909241523182557217671'
  # 登陆账号密码
  login_iphone:  '13521883086'
  login_password: 'a111111'
# PRO生产环境
PRO:
  baseURL: 'local输入'
  # 订单号
  orderdetail: 'local输入CM1909121313579018714717'
  # 登陆账号密码
  login_iphone:  'local输入'
  login_password: 'local输入'
# 钉钉
access_token: '需要输入'
#####以上需要复制到config_local.yml中进行配置#####

# 兼容浏览器 目前仅调试Chrome,
browser: Chrome
#  Firefox
# 集合URL
set_url: '/orderdetail?sn=${orderdetail}&status=live'

# 输入的竞买额
input_price: '0.01'
# 下一场间隔时间，单位秒
auction_interval_time: 120
# 购买后清场时间，单位秒 + 60秒先sleep的时间 共460秒，是否购买成功的时间确认
auction_clear_time: 400

# 时间样式
ISOTIMEFORMAT: '%Y%m%d%H%M%S'
#运维要求日志格式，部分字段名称待合规
log:
  formatter: "{timestamp:%(asctime)s,name:%(name)s,level:%(levelname)s, message: %(message)s,filename:[%(filename)s,lineno:%(lineno)s]}"
  file_handler: INFO
  console_handler: DEBUG